ALTER TABLE products
ADD COLUMN IF NOT EXISTS imposto_percentual NUMERIC(8,4) NOT NULL DEFAULT 0;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS taxa_cartao_percentual NUMERIC(8,4) NOT NULL DEFAULT 0;
